### PR TITLE
Fix not allowing from token as market/country

### LINKED ISSUE #28: "from_token" is currently not a valid parameter
Hey,

thanks for your work on the library. I'm currently trying to search for tracks using rspotify. According to the documentation, `from_token` can be passed as a `market` parameter to search in the market tied to the token.

However, the `search_*` functions seem to require an Option<Country> parameter. There seems to be no Country enum representing `from_token`, unless I am missing something?

### PR DESCRIPTION
**Pull request by Qluxzz**
## Description

Fixes "from_token" not being a valid option for market/country.

Create Market enum which can be a country or from_token in order to satisfy both conditions.

Update usages of Country to instead use Market enum.

Update mentions and parameters of country/market to be consistent with spotify API docs.

Fixes #28 

## Motivation and Context

To allow market to be automatically selected from the users access-token instead of having to be supplied manually.

## Type of change

Please delete options that are not relevant.

- [X] This change requires a documentation update
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

Please also list any relevant details for your test configuration:
I ran all tests but the most interesting ones would be the following since they used the old Country enum

- [X] ```Market::Country```: test_artist_top_tracks
- [X] ```Market::Country```: test_categories
- [X] ```Market::Country```: test_category_playlists
- [X] ```Market::Country```: test_recommendations
- [X] ```Market::Country```: test_search_artist

I've also added a test that uses Market::FromToken functionality, but since the market supplied is not static and changes with the oauth token credentials, it maybe wouldn't be such a good test?
- [X] ```Market::FromToken```: test_search_artist_with_from_token

### CODE REVIEW

File: src/model/enums/misc.rs [hunk 1]
```diff
@@ -91,3 +93,20 @@ pub enum Modality {
...
+/// Limit the response to a particular market
+///
+/// FromToken is the same thing as setting the market parameter to the user's country.
+#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
+pub enum Market {
+    Country(Country),
+    FromToken,
+}
+
+impl Into<String> for Market {
```
Comment (Qluxzz) [inline src/model/enums/misc.rs:105]: Should this be moved somewhere else in order to keep this file to only declarations of enums?

File: src/client.rs [hunk 2]
```diff
@@ -316,20 +316,18 @@ impl Spotify {
     ///
     /// Parameters:
     /// - artist_id - the artist ID, URI or URL
-    /// - country - limit the response to one particular country.
+    /// - market - limit the response to one particular country.
     ///
     /// [Reference](https://developer.spotify.com/web-api/get-artists-top-tracks/)
     #[maybe_async]
-    pub async fn artist_top_tracks<T: Into<Option<Country>>>(
+    pub async fn artist_top_tracks<T: Into<Market>>(
```
Comment (marioortizmanero) [inline src/client.rs:323]: You can remove this `Into<Market>` and just use `Market`, as `Market` doesn't implement methods like `From<String>` AFAIK. This `Into` was used previously to avoid `Some` when passing optional parameters, but this decision is being discussed at #134 anyway (you can take a look and leave your opinion if you like :))

File: src/model/enums/misc.rs (hunk 1 above)
Comment (marioortizmanero) [reply src/model/enums/misc.rs:105]: Nah I would say it's ok

Comment (marioortizmanero) [reply src/model/enums/misc.rs:105]: As as side note: can you add a new line between the previous enum and this one? Thanks

**Review by marioortizmanero — COMMENTED** [review]
I think the test you added is OK, since we can't check the results anyway. As long as it makes sure it doesn't break it's enough for now.

File: src/model/enums/misc.rs [hunk 3]
```diff
@@ -91,3 +93,21 @@ pub enum Modality {
...
```
Comment (marioortizmanero) [inline src/model/enums/misc.rs:106]: Why not use `ToString` instead of `Into<String>` by the way? That way you can use `market.to_string`, which:

* Avoids type inference issues (I saw a case where you had to declare `market: String` to let Rust know it's `Into::<String>`)
* `to_string` is more explicit and easier to understand for the reader
* The struct is borrowed instead of moved, so you can keep using it

Comment (Qluxzz) [reply src/model/enums/misc.rs:106]: Good question, guess I didn't really think about it. I'll fix it.

**Comment by ramsayleung** [comment]
Is this PR is ready to merge, it seems there is no more update after the last commit?

**Comment by Qluxzz** [comment]
Yes, I implemented the to_string trait instead of into trait as @marioortizmanero asked me about, and then requested a review.

**Comment by marioortizmanero** [comment]
Yes sorry! I was busy but I'm finally done with finals. Merging this, thanks for the contribution :)

**Review by marioortizmanero — APPROVED** [review]

**Comment by Qluxzz** [comment]
@marioortizmanero no worries, hope you aced your finals!
